### ISSUE TITLE
播放下架歌曲有问题，不知道是不是我姿势不对

### ISSUE THREAD

**Issue by mittjie** [Chion82/163-music-unlock#16]
我也不懂这个，只是在阿里云部署了一下，一般歌曲没有问题，播放下架歌曲就会这样
终端信息
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/server/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/home/server/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/home/server/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Chion82** [comment]
不是你的姿势有问题。。。是因为网易今天把API修了，现在这个脚本已经不能获取到下架音乐的信息了。
如果希望继续听下架歌曲，可以使用作者维护的host。具体用了什么黑科技这里就不方便公开了，闷声发大财。。。嘿嘿
