### ISSUE TITLE
自己搭建服务器后无法播放

### ISSUE THREAD

**Issue by evindu** [Chion82/163-music-unlock#22]
是不是不能用python2.7   ？
python runapi.py
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 269-684-276
127.0.0.1 - - [24/Apr/2016 13:58:45] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)

  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))

  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])

TypeError: 'NoneType' object has no attribute '__getitem__'

127.0.0.1 - - [24/Apr/2016 13:58:45] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)

  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:46] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:46] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:47] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:48] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:48] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:49] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:49] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:51] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:51] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'
127.0.0.1 - - [24/Apr/2016 13:58:51] "POST /eapi/song/enhance/player/url HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/music/runapi.py", line 24, in get_song_api
    return get_ios_response(player_or_download)
  File "/root/music/runapi.py", line 60, in get_ios_response
    return jsonify(get_music_resource(song_id, player_or_download))
  File "/root/music/runapi.py", line 73, in get_music_resource
    song_res_id = str(song_res['dfsId'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Chion82** [comment]
由于网易的修补，这个版本的脚本已经无法获取到歌曲文件的播放地址。公共服务器上使用了其他方法，为延长这个项目的可用时间，暂不公开公共服务器上运行的真实版本。
